In [19]:
import numpy as np
import open3d as o3d

def read_points3D_bin(file_path):
    with open(file_path, "rb") as f:
        num_points = np.fromfile(f, dtype=np.uint64, count=1)[0]
        data = np.fromfile(f, dtype=np.float64, count=num_points * 3).reshape(-1, 3)
    return data

points3D = read_points3D_bin("colmap_points3D.bin")
print(points3D)


[[ 3.28606520e-318  3.25967927e+000  1.28876255e+000]
 [ 1.52123377e+000 -1.68941661e-012  2.92187268e-315]
 [ 2.75164619e-135 -6.98351808e-251 -1.91562232e+053]
 ...
 [ 3.86407436e+025  2.11176905e+133  1.05234006e-318]
 [ 1.06692420e-159  2.98558340e-083  4.32000225e-089]
 [ 1.61753934e-313  4.19901470e+206  6.63739054e+034]]


In [20]:
# 转换为 Open3D 的点云对象
pcd1 = o3d.geometry.PointCloud()
pcd1.points = o3d.utility.Vector3dVector(points3D)
len(pcd1.points)

520723

In [23]:
# 读取 PLY 文件
pcd2 = o3d.io.read_point_cloud("colmap_glacier.ply")
len(pcd2.points)

520723

In [25]:
pcd2.voxel_down_sample(0.05)

PointCloud with 97182 points.